import 'package:recipe_book_app/core/models/recipe_model.dart';

List<RecipeModel> dummyRecipes = [
  RecipeModel(
    id: '1',
    title: 'Pasta Bolognese',
    description: 'Italian lunch with rich meat sauce',
    imageUrl: '',
    rating: 4.9,
    durationInMinutes: 35,
    difficulty: 'Medium',
    category: 'Lunch',
    ingredients: ['Pasta', 'Minced Meat', 'Tomato Sauce', 'Onion', 'Garlic'],
    instructions: [
      'Heat oil in a large pot or deep skillet over medium high heat. Add onion and garlic, cook for 3 minutes or until light golden and softened.',
      'Cook beef – Turn heat up to high and add beef. Cook, breaking it up as your go, until browned.',
      'Adding the sauce: Add the tomato paste and stir for two minutes, then add the tomato purée, broth, a splash of milk, salt, and pepper.',
      'Reducing and Concentrating: Bring the mixture to a boil, then reduce the heat and let it simmer for at least 30 minutes until the sauce thickens and becomes rich.',
      'Cooking the pasta: Meanwhile, bring a large pot of generously salted water to a boil and cook the pasta until *al dente* (slightly firm), following the package instructions.',
      'Mixing and Serving: Drain the pasta and add it directly to the Bolognese sauce; toss for a minute to allow it to absorb the flavors, then serve hot with Parmesan cheese.',
    ],
  ),
  // ==================== BREAKFAST (8) ====================
  RecipeModel(
    id: 'b1',
    title: 'Shakshuka',
    description:
        'Middle Eastern poached eggs in a spiced tomato and pepper sauce',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa',
    rating: 4.8,
    durationInMinutes: 25,
    difficulty: 'Easy',
    category: 'Breakfast',
    ingredients: [
      'Eggs',
      'Tomatoes',
      'Bell Pepper',
      'Onion',
      'Garlic',
      'Cumin',
      'Olive Oil',
    ],
    instructions: [
      'Sauté chopped onion, garlic, and bell pepper in olive oil until soft.',
      'Add crushed tomatoes, cumin, paprika, salt, and pepper; simmer for 10 minutes.',
      'Make small wells in the sauce and crack the eggs directly into them.',
      'Cover the pan and cook on low heat until egg whites are set but yolks remain runny.',
      'Garnish with fresh parsley and serve hot with warm pita bread.',
    ],
  ),
  RecipeModel(
    id: 'b2',
    title: 'Egyptian Ful Medames',
    description: 'Hearty fava bean dip seasoned with garlic, lemon, and cumin',
    imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea',
    rating: 4.7,
    durationInMinutes: 15,
    difficulty: 'Easy',
    category: 'Breakfast',
    ingredients: [
      'Fava Beans',
      'Garlic',
      'Lemon Juice',
      'Cumin',
      'Olive Oil',
      'Tahini',
    ],
    instructions: [
      'Warm cooked fava beans in a small pot over medium heat.',
      'Lightly mash the beans using a fork or potato masher.',
      'Stir in crushed garlic, lemon juice, ground cumin, and tahini.',
      'Drizzle generously with extra virgin olive oil and serve with sliced cucumbers and flatbread.',
    ],
  ),
  RecipeModel(
    id: 'b3',
    title: 'Turkish Menemen',
    description:
        'Soft scrambled eggs cooked with juicy tomatoes and green peppers',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8',
    rating: 4.6,
    durationInMinutes: 20,
    difficulty: 'Easy',
    category: 'breakfast',
    ingredients: [
      'Eggs',
      'Tomatoes',
      'Green Peppers',
      'Butter',
      'Red Pepper Flakes',
      'Salt',
    ],
    instructions: [
      'Melt butter in a pan and sauté finely diced green peppers until tender.',
      'Add peeled, diced tomatoes and cook until they release juices and turn soft.',
      'Whisk eggs lightly in a bowl and pour into the tomato-pepper mixture.',
      'Gently fold the eggs on low heat until barely set, keeping them soft and creamy.',
    ],
  ),
  RecipeModel(
    id: 'b4',
    title: 'Korean Egg Drop Sandwich',
    description: 'Fluffy scrambled eggs and sweet mayo in thick toasted bread',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349',
    rating: 4.9,
    durationInMinutes: 15,
    difficulty: 'Easy',
    category: 'breakfast',
    ingredients: [
      'Brioche Toast',
      'Eggs',
      'Condensed Milk',
      'Mayonnaise',
      'Butter',
      'Cheddar Slice',
    ],
    instructions: [
      'Toast thick slices of bread in butter until golden brown.',
      'Whisk eggs with a splash of milk and scramble gently in a buttered pan.',
      'Mix mayonnaise and condensed milk to make a sweet Korean sauce.',
      'Spread sauce on toast, layer with cheddar cheese and soft scrambled eggs.',
    ],
  ),
  RecipeModel(
    id: 'b5',
    title: 'Halal Full English Breakfast',
    description: 'Classic British breakfast with beef sausages and baked beans',
    imageUrl: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666',
    rating: 4.8,
    durationInMinutes: 30,
    difficulty: 'Medium',
    category: 'breakfast',
    ingredients: [
      'Halal Beef Sausages',
      'Eggs',
      'Baked Beans',
      'Tomatoes',
      'Mushrooms',
      'Toast',
    ],
    instructions: [
      'Pan-fry Halal beef sausages until cooked through and golden brown.',
      'Sauté whole mushrooms and sliced tomatoes in a little butter.',
      'Warm baked beans in a small saucepan.',
      'Fry or poach eggs to your liking and toast the bread slices.',
      'Plate all components together hot with buttered toast.',
    ],
  ),
  RecipeModel(
    id: 'b6',
    title: 'Chinese Congee (Rice Porridge)',
    description:
        'Comforting savoury rice porridge topped with chicken and ginger',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554',
    rating: 4.5,
    durationInMinutes: 50,
    difficulty: 'Easy',
    category: 'breakfast',
    ingredients: [
      'Jasmine Rice',
      'Chicken Broth',
      'Shredded Chicken',
      'Ginger',
      'Green Onions',
      'Sesame Oil',
    ],
    instructions: [
      'Rinse rice and bring to a boil in chicken broth with thin ginger slices.',
      'Reduce heat to low, cover partially, and simmer for 40 minutes until broken down and silky.',
      'Stir in shredded cooked chicken and season with salt and white pepper.',
      'Drizzle with sesame oil and garnish with chopped green onions before serving.',
    ],
  ),
  RecipeModel(
    id: 'b7',
    title: 'Moroccan Baghrir (Thousand Hole Pancakes)',
    description: 'Spongy semolina pancakes served with warm honey butter syrup',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445',
    rating: 4.7,
    durationInMinutes: 30,
    difficulty: 'Medium',
    category: 'breakfast',
    ingredients: [
      'Fine Semolina',
      'Flour',
      'Yeast',
      'Baking Powder',
      'Warm Water',
      'Honey',
      'Butter',
    ],
    instructions: [
      'Blend semolina, flour, yeast, baking powder, and warm water until smooth.',
      'Let batter rest for 15 minutes until small bubbles form on top.',
      'Pour batter into a non-stick pan over medium heat; cook on one side only until top dries and holes appear.',
      'Melt butter with honey and drizzle generously over warm pancakes.',
    ],
  ),
  RecipeModel(
    id: 'b8',
    title: 'Lebanese Manakish Zaatar',
    description:
        'Flatbread topped with aromatic thyme, sesame, and olive oil paste',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    rating: 4.9,
    durationInMinutes: 35,
    difficulty: 'Medium',
    category: 'breakfast',
    ingredients: [
      'Flour',
      'Yeast',
      'Zaatar Mix',
      'Olive Oil',
      'Sugar',
      'Warm Water',
    ],
    instructions: [
      'Prepare yeast dough with flour, sugar, water, and olive oil; let rise for 30 minutes.',
      'Mix Zaatar spice blend with extra virgin olive oil into a spreadable paste.',
      'Roll dough into flat rounds and spread the Zaatar mixture evenly on top.',
      'Bake at 220°C (425°F) for 8–10 minutes until edges are crisp.',
    ],
  ),

  // ==================== LUNCH (8) ====================
  RecipeModel(
    id: 'l1',
    title: 'Chicken Kabsa',
    description:
        'Saudi Arabia national rice dish with spiced chicken and roasted nuts',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8',
    rating: 4.9,
    durationInMinutes: 60,
    difficulty: 'Medium',
    category: 'Lunch',
    ingredients: [
      'Chicken',
      'Basmati Rice',
      'Kabsa Spice Mix',
      'Tomatoes',
      'Onions',
      'Almonds',
      'Raisins',
    ],
    instructions: [
      'Sauté onions and garlic; add chicken pieces and brown all sides.',
      'Add tomato paste, pureed tomatoes, whole spices, and Kabsa seasoning blend.',
      'Pour water over chicken and simmer until tender; remove chicken and roast in oven until crisp.',
      'Cook soaked basmati rice in the remaining fragrant chicken broth.',
      'Serve rice topped with roasted chicken, toasted almonds, and raisins.',
    ],
  ),
  RecipeModel(
    id: 'l2',
    title: 'Korean Beef Bulgogi',
    description:
        'Sweet and savoury marinated sliced beef served over steamed rice',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947',
    rating: 4.8,
    durationInMinutes: 40,
    difficulty: 'Medium',
    category: 'lunch',
    ingredients: [
      'Halal Beef Sirloin',
      'Soy Sauce',
      'Grated Pear',
      'Garlic',
      'Sesame Oil',
      'Green Onions',
    ],
    instructions: [
      'Thinly slice beef against the grain.',
      'Whisk soy sauce, grated pear, minced garlic, brown sugar, and sesame oil.',
      'Marinate beef slices for at least 30 minutes.',
      'Stir-fry beef in a piping hot skillet in small batches until caramelized.',
      'Garnish with sesame seeds and green onions; serve with hot white rice.',
    ],
  ),
  RecipeModel(
    id: 'l3',
    title: 'Egyptian Koshary',
    description:
        'National Egyptian dish with rice, lentils, pasta, and spicy tomato sauce',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    rating: 4.7,
    durationInMinutes: 50,
    difficulty: 'Hard',
    category: 'lunch',
    ingredients: [
      'Rice',
      'Brown Lentils',
      'Macaroni',
      'Chickpeas',
      'Garlic Vinegar Sauce',
      'Crispy Onions',
    ],
    instructions: [
      'Cook brown lentils and rice together with cumin and salt.',
      'Boil elbow macaroni and warm up canned chickpeas separately.',
      'Prepare spicy tomato sauce with fried garlic, vinegar, and chilli powder.',
      'Layer rice/lentil mix, macaroni, chickpeas, tomato sauce, and garlic vinegar liquid.',
      'Top heavily with crispy fried onions before serving.',
    ],
  ),
  RecipeModel(
    id: 'l4',
    title: 'Halal Chicken Tikka Masala',
    description:
        'British-Indian classic chicken chunks in a rich creamy tomato sauce',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641',
    rating: 4.9,
    durationInMinutes: 45,
    difficulty: 'Medium',
    category: 'lunch',
    ingredients: [
      'Chicken Thighs',
      'Yogurt',
      'Garam Masala',
      'Tomato Sauce',
      'Heavy Cream',
      'Garlic',
      'Ginger',
    ],
    instructions: [
      'Marinate chicken pieces in yogurt, lemon, garlic, ginger, and spices for 1 hour.',
      'Sear or broil chicken pieces until charred around the edges.',
      'Build sauce by frying onions, ginger, garlic, tomato sauce, and Garam Masala.',
      'Pour in heavy cream, add chicken back to sauce, and simmer for 15 minutes.',
    ],
  ),
  RecipeModel(
    id: 'l5',
    title: 'Chinese Beef Chow Mein',
    description: 'Stir-fried egg noodles with sliced beef and crisp vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246',
    rating: 4.6,
    durationInMinutes: 25,
    difficulty: 'Easy',
    category: 'lunch',
    ingredients: [
      'Halal Flank Steak',
      'Chow Mein Noodles',
      'Soy Sauce',
      'Oyster Sauce',
      'Cabbage',
      'Carrots',
    ],
    instructions: [
      'Boil noodles according to package instructions and drain.',
      'Marinate sliced beef in soy sauce, cornstarch, and sesame oil.',
      'Sear beef in a wok on high heat until browned; set aside.',
      'Stir-fry shredded cabbage and carrots; add noodles, stir-fry sauce, and beef back into wok.',
    ],
  ),
  RecipeModel(
    id: 'l6',
    title: 'Moroccan Lamb Tagine',
    description:
        'Slow-cooked sweet and savoury lamb stew with prunes and almonds',
    imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea',
    rating: 4.8,
    durationInMinutes: 90,
    difficulty: 'Hard',
    category: 'lunch',
    ingredients: [
      'Halal Lamb Shoulder',
      'Dried Prunes',
      'Cinnamon',
      'Saffron',
      'Honey',
      'Toasted Almonds',
    ],
    instructions: [
      'Sear lamb chunks in a tagine or heavy pot with olive oil.',
      'Add chopped onions, saffron, cinnamon sticks, ginger, and broth; cover and simmer for 1 hour.',
      'Add dried prunes and honey; simmer uncovered for 20 minutes until sauce thickens.',
      'Garnish with toasted sesame seeds and fried almonds.',
    ],
  ),
  RecipeModel(
    id: 'l7',
    title: 'Palestinian Musakhan',
    description:
        'Roast chicken on flatbread coated with sumac, caramelised onions, and pine nuts',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d',
    rating: 4.9,
    durationInMinutes: 55,
    difficulty: 'Medium',
    category: 'lunch',
    ingredients: [
      'Chicken',
      'Sumac',
      'Onions',
      'Olive Oil',
      'Taboon Bread',
      'Pine Nuts',
    ],
    instructions: [
      'Boil chicken with cardamom and bay leaf until tender, then rub with sumac and oil.',
      'Cook large amounts of sliced onions in olive oil on low heat until soft.',
      'Stir abundant sumac and pine nuts into onions.',
      'Dip Taboon bread in onion oil, layer with cooked onions, top with chicken, and bake until crispy.',
    ],
  ),
  RecipeModel(
    id: 'l8',
    title: 'Korean Bibimbap',
    description:
        'Mixed rice bowl topped with seasoned vegetables, beef, and Gochujang',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733',
    rating: 4.8,
    durationInMinutes: 40,
    difficulty: 'Medium',
    category: 'lunch',
    ingredients: [
      'Rice',
      'Ground Beef',
      'Spinach',
      'Bean Sprouts',
      'Zucchini',
      'Egg',
      'Gochujang Paste',
    ],
    instructions: [
      'Sauté vegetables separately with sesame oil and garlic.',
      'Cook ground beef in soy sauce and sweet seasoning mix.',
      'Assemble warm rice in a bowl and arrange vegetables and beef neatly around the edge.',
      'Top with a fried egg and a scoop of Gochujang red pepper sauce.',
    ],
  ),

  // ==================== DRINKES (8) ====================
  RecipeModel(
    id: 'd1',
    title: 'Karak Tea',
    description:
        'Spiced Gulf milk tea brewed with cardamom, cloves, and evaporated milk',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3',
    rating: 4.9,
    durationInMinutes: 15,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'Black Tea Loose',
      'Evaporated Milk',
      'Cardamom Pods',
      'Cloves',
      'Saffron',
      'Sugar',
    ],
    instructions: [
      'Boil water with crushed cardamom pods, cloves, and loose black tea for 5 minutes.',
      'Pour in evaporated milk and sugar to taste.',
      'Simmer on low heat for 8 minutes to allow tea to thicken and turn caramel-colored.',
      'Strain into cups and serve hot.',
    ],
  ),
  RecipeModel(
    id: 'd2',
    title: 'Arabic Mint Lemonade (Limonana)',
    description: 'Ultra-refreshing blended lemon juice and fresh mint smoothie',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd',
    rating: 4.8,
    durationInMinutes: 10,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'Fresh Lemon Juice',
      'Mint Leaves',
      'Sugar Syrup',
      'Ice Cubes',
      'Water',
    ],
    instructions: [
      'Add lemon juice, fresh mint leaves, sugar syrup, and water to a high-speed blender.',
      'Add crushed ice and blend until smooth and slushy.',
      'Pour into tall glasses and garnish with a sprig of mint.',
    ],
  ),
  RecipeModel(
    id: 'd3',
    title: 'Moroccan Mint Tea',
    description:
        'Traditional green tea infused with abundant fresh spearmint leaves',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574',
    rating: 4.7,
    durationInMinutes: 15,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'Gunpowder Green Tea',
      'Fresh Spearmint',
      'Sugar',
      'Boiling Water',
    ],
    instructions: [
      'Rinse green tea leaves with boiling water in a teapot.',
      'Add fresh spearmint sprigs and sugar lumps to the pot.',
      'Fill with boiling water and simmer on low heat for 5 minutes.',
      'Pour from high above the glass to create a delicate foam top.',
    ],
  ),
  RecipeModel(
    id: 'd4',
    title: 'Korean Banana Milk',
    description: 'Sweet and creamy homemade Korean banana-flavored milk drink',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150',
    rating: 4.6,
    durationInMinutes: 5,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'Ripe Banana',
      'Fresh Whole Milk',
      'Maple Syrup',
      'Vanilla Extract',
    ],
    instructions: [
      'Peel and slice a ripe banana.',
      'Place banana, cold milk, maple syrup, and vanilla into a blender.',
      'Blend on high until silky and smooth with no fruit lumps remaining.',
    ],
  ),
  RecipeModel(
    id: 'd5',
    title: 'British Iced Lemon Tea',
    description:
        'Classic cold brewed black tea with fresh lemon slices and sugar',
    imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87',
    rating: 4.5,
    durationInMinutes: 10,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'English Breakfast Tea',
      'Lemons',
      'Honey or Sugar',
      'Ice Cubes',
    ],
    instructions: [
      'Steep black tea bags in hot water for 5 minutes, then discard tea bags.',
      'Stir in sweetener while tea is still warm.',
      'Chill tea in refrigerator, then pour over tall glasses filled with ice.',
      'Squeeze fresh lemon juice into glasses and drop in lemon slices.',
    ],
  ),
  RecipeModel(
    id: 'd6',
    title: 'Egyptian Sahlab',
    description:
        'Warm, thick milk drink flavored with rosewater and crushed nuts',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699',
    rating: 4.8,
    durationInMinutes: 15,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'Milk',
      'Cornstarch',
      'Sugar',
      'Rosewater',
      'Cinnamon',
      'Pistachios',
      'Coconut Flakes',
    ],
    instructions: [
      'Whisk cornstarch and sugar into cold milk until dissolved.',
      'Heat mixture over medium heat, stirring continuously until thickened.',
      'Remove from heat and stir in rosewater.',
      'Pour into mugs and dust generously with cinnamon, crushed pistachios, and coconut.',
    ],
  ),
  RecipeModel(
    id: 'd7',
    title: 'Chinese Jasmine Green Tea',
    description: 'Delicate floral tea infused with fresh jasmine blossom aroma',
    imageUrl: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12',
    rating: 4.6,
    durationInMinutes: 5,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: ['Jasmine Green Tea Leaves', 'Hot Water'],
    instructions: [
      'Heat water to 80°C (175°F) – do not boil completely.',
      'Place jasmine tea leaves into a teapot or infuser.',
      'Pour water over leaves and steep for 2 to 3 minutes.',
      'Strain into teacups and enjoy warm without added sweetener.',
    ],
  ),
  RecipeModel(
    id: 'd8',
    title: 'Avocado Honey Smoothie (Arabic Style)',
    description: 'Rich and creamy avocado shake layered with honey and nuts',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888',
    rating: 4.9,
    durationInMinutes: 10,
    difficulty: 'Easy',
    category: 'drinkes',
    ingredients: [
      'Ripe Avocado',
      'Cold Milk',
      'Honey',
      'Ice',
      'Crushed Almonds',
    ],
    instructions: [
      'Scoop avocado flesh into blender.',
      'Add cold milk, honey, and ice cubes.',
      'Blend until velvety thick.',
      'Drizzle glass walls with honey, pour smoothie, and top with crushed almonds.',
    ],
  ),

  // ==================== DISERTS (8) ====================
  RecipeModel(
    id: 'ds1',
    title: 'Kunafa Nabulsiya',
    description:
        'Crispy shredded pastry stuffed with gooey cheese and soaked in sugar syrup',
    imageUrl: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c',
    rating: 4.9,
    durationInMinutes: 45,
    difficulty: 'Medium',
    category: 'diserts',
    ingredients: [
      'Kataifi Dough',
      'Ghee',
      'Nabulsi or Akkawi Cheese',
      'Sugar Syrup',
      'Pistachios',
    ],
    instructions: [
      'Shred kataifi pastry dough finely and mix thoroughly with melted ghee.',
      'Press half the dough into a baking pan.',
      'Layer desalted cheese over the dough and top with remaining pastry.',
      'Bake until golden and crisp; invert pan onto a serving plate.',
      'Pour warm orange-blossom sugar syrup over top and decorate with crushed pistachios.',
    ],
  ),
  RecipeModel(
    id: 'ds2',
    title: 'Egyptian Umm Ali',
    description:
        'Warm bread pudding made with puff pastry, milk, nuts, and raisins',
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814',
    rating: 4.8,
    durationInMinutes: 35,
    difficulty: 'Easy',
    category: 'diserts',
    ingredients: [
      'Puff Pastry',
      'Milk',
      'Condensed Milk',
      'Heavy Cream',
      'Mixed Nuts',
      'Raisins',
    ],
    instructions: [
      'Bake puff pastry sheets until crisp, then break into small pieces into a baking dish.',
      'Toss in raisins, coconut, and chopped pistachios/almonds.',
      'Heat milk with sugar and vanilla; pour hot milk over pastry mixture.',
      'Spread cream on top and broil in oven until top layer turns bubbly and golden brown.',
    ],
  ),
  RecipeModel(
    id: 'ds3',
    title: 'Korean Hotteok (Sweet Pancakes)',
    description:
        'Pan-fried yeast pancakes filled with melted brown sugar and cinnamon nuts',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
    rating: 4.9,
    durationInMinutes: 40,
    difficulty: 'Medium',
    category: 'diserts',
    ingredients: [
      'Flour',
      'Yeast',
      'Brown Sugar',
      'Cinnamon',
      'Chopped Walnuts',
      'Vegetable Oil',
    ],
    instructions: [
      'Make a soft yeast dough and allow it to rise for 1 hour.',
      'Combine brown sugar, cinnamon, and chopped walnuts for filling.',
      'Flatten small balls of dough, insert filling, and seal into a ball.',
      'Pan-fry in oil, flattening with a spatula until golden brown on both sides.',
    ],
  ),
  RecipeModel(
    id: 'ds4',
    title: 'British Sticky Toffee Pudding',
    description: 'Moist date cake drenched in a rich warm butterscotch sauce',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c',
    rating: 4.8,
    durationInMinutes: 50,
    difficulty: 'Medium',
    category: 'diserts',
    ingredients: [
      'Pitted Dates',
      'Baking Soda',
      'Butter',
      'Brown Sugar',
      'Eggs',
      'Heavy Cream',
    ],
    instructions: [
      'Soak dates in boiling water with baking soda, then puree.',
      'Cream butter and brown sugar, beat in eggs, then stir in date puree and flour.',
      'Bake in ramekins for 25 minutes.',
      'Melt butter, brown sugar, and cream together to make sticky sauce.',
      'Pour warm sauce over warm cakes and serve with vanilla ice cream.',
    ],
  ),
  RecipeModel(
    id: 'ds5',
    title: 'Lebanese Maamoul',
    description: 'Shortbread cookies filled with spiced date paste or nuts',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
    rating: 4.7,
    durationInMinutes: 60,
    difficulty: 'Hard',
    category: 'diserts',
    ingredients: [
      'Semolina',
      'Ghee',
      'Rosewater',
      'Date Paste',
      'Walnuts',
      'Powdered Sugar',
    ],
    instructions: [
      'Knead semolina, ghee, and rosewater into a dough; rest overnight.',
      'Prepare date paste filling with cinnamon and nutmeg.',
      'Stuff small dough portions with date paste and press into carved wooden molds.',
      'Bake at high temperature until lightly golden; dust with powdered sugar when cool.',
    ],
  ),
  RecipeModel(
    id: 'ds6',
    title: 'Chinese Mango Sago Pudding',
    description:
        'Chilled tropical dessert with sweet mango, coconut milk, and sago pearls',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55',
    rating: 4.7,
    durationInMinutes: 20,
    difficulty: 'Easy',
    category: 'diserts',
    ingredients: [
      'Ripe Mangoes',
      'Small Tapioca Sago Pearls',
      'Coconut Milk',
      'Evaporated Milk',
      'Sugar',
    ],
    instructions: [
      'Boil sago pearls until translucent; drain and rinse in cold water.',
      'Blend half the mangoes with coconut milk and sugar until smooth.',
      'Dice remaining mangoes into small cubes.',
      'Mix mango puree with cooked sago and diced mangoes; chill in fridge before serving.',
    ],
  ),
  RecipeModel(
    id: 'ds7',
    title: 'Turkish Baklava',
    description:
        'Crispy layers of filo pastry filled with chopped nuts and honey syrup',
    imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548',
    rating: 4.9,
    durationInMinutes: 75,
    difficulty: 'Hard',
    category: 'diserts',
    ingredients: [
      'Filo Pastry',
      'Melted Butter',
      'Pistachios',
      'Sugar Syrup',
      'Lemon Juice',
    ],
    instructions: [
      'Layer filo sheets in a baking pan, brushing each with melted butter.',
      'Spread finely chopped pistachios in the middle layer.',
      'Top with remaining buttered filo sheets and cut into diamond shapes.',
      'Bake until crisp and golden brown.',
      'Pour cooled lemon sugar syrup over hot baklava immediately.',
    ],
  ),
  RecipeModel(
    id: 'ds8',
    title: 'Basbousa (Semolina Cake)',
    description: 'Moist Arabic semolina cake soaked in sweet rose syrup',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
    rating: 4.6,
    durationInMinutes: 40,
    difficulty: 'Easy',
    category: 'diserts',
    ingredients: [
      'Semolina',
      'Yogurt',
      'Melted Butter',
      'Sugar Syrup',
      'Blanched Almonds',
    ],
    instructions: [
      'Mix semolina, sugar, yogurt, and melted butter into a thick batter.',
      'Spread evenly into a greased baking dish and score into diamond shapes.',
      'Place a blanched almond in the center of each diamond.',
      'Bake at 190°C (375°F) for 30 minutes until golden brown.',
      'Pour warm sugar syrup over the cake immediately after removing from oven.',
    ],
  ),
];
